server:
  port: 3001

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Work/native-file-repo
        git:
          uri: https://github.com/byeon-jiun/spring-cloud-config.git
#          uri: file:///Users/byeonjiun/Desktop/Work/git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
