server:
  port: 3001

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/byeon-jiun/spring-cloud-config.git
#          uri: file:///Users/byeonjiun/Desktop/Work/git-local-repo
